### ISSUE TITLE
ImportError: lxml.html.clean module is now a separate project lxml_html_clean. (simple additional install with pip fixes it)

### ISSUE THREAD

**Issue by tgaldes** [gregpr07/browser-use#10]
On ubuntu 20.04, running python3.11 in a virtual env

to recreate:
clone repo, start virtual env, pip install .

run the example provided gets the error:

(env) tgaldes@tyler:~/git/3rdparty/browser-use$ python examples/try.py "Go to hackernews on show hn and give me top 10 post titles, their points and hours. Calculate for each the ratio of points per hour. " --provider openai
Traceback (most recent call last):
  File "/home/tgaldes/git/3rdparty/browser-use/examples/try.py", line 19, in <module>
    from browser_use import Agent
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/browser_use/__init__.py", line 1, in <module>
    from browser_use.agent.service import AgentService as Agent
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/browser_use/agent/service.py", line 16, in <module>
    from browser_use.controller.service import ControllerService
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/browser_use/controller/service.py", line 1, in <module>
    from browser_use.browser.service import BrowserService
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/browser_use/browser/service.py", line 12, in <module>
    from main_content_extractor import MainContentExtractor
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/main_content_extractor/__init__.py", line 1, in <module>
    from main_content_extractor.main_content_extractor import *
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/main_content_extractor/main_content_extractor.py", line 4, in <module>
    from .trafilatura_extends import TrafilaturaExtends
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/main_content_extractor/trafilatura_extends.py", line 3, in <module>
    import trafilatura
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/trafilatura/__init__.py", line 18, in <module>
    from .core import bare_extraction, extract, process_record
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/trafilatura/core.py", line 16, in <module>
    from .external import compare_extraction
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/trafilatura/external.py", line 9, in <module>
    from justext.core import (ParagraphMaker, classify_paragraphs,
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/justext/__init__.py", line 12, in <module>
    from .core import justext
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/justext/core.py", line 21, in <module>
    from lxml.html.clean import Cleaner
  File "/home/tgaldes/git/3rdparty/browser-use/env/lib/python3.11/site-packages/lxml/html/clean.py", line 18, in <module>
    raise ImportError(
ImportError: lxml.html.clean module is now a separate project lxml_html_clean.
Install lxml[html_clean] or lxml_html_clean directly.

HERE IS THE FIX
(env) tgaldes@tyler:~/git/3rdparty/browser-use$ pip3 install lxml_html_clean
Collecting lxml_html_clean
  Downloading lxml_html_clean-0.3.1-py3-none-any.whl (13 kB)
Requirement already satisfied: lxml in ./env/lib/python3.11/site-packages (from lxml_html_clean) (5.3.0)
Installing collected packages: lxml_html_clean
Successfully installed lxml_html_clean-0.3.1

And now it worked! yay
(env) tgaldes@tyler:~/git/3rdparty/browser-use$ python examples/try.py "Go to hackernews on show hn and give me top 10 post titles, their points and hours. Calculate for each the ratio of points per hour. " --provider openai
INFO:browser_use.agent.service:
.......

**Comment by tgaldes** [comment]
https://github.com/gregpr07/browser-use/pull/11 ?

**Comment by MagMueller** [comment]
Thank you very much!
